apps/wsdjs_web/lib/wsdjs_web/router.ex
defmodule WsdjsWeb.Router do
  use WsdjsWeb, :router

  pipeline :browser do
    plug(:accepts, ["html", "text"])
    plug(:fetch_session)
    plug(:fetch_flash)
    plug(:protect_from_forgery)
    plug(:put_secure_browser_headers)
    plug(WsdjsWeb.VerifySession)
    plug(WsdjsWeb.IsAjax)
  end

  pipeline :browser_auth do
    plug(WsdjsWeb.EnsureAuthenticated)
  end

  pipeline :api do
    plug(:accepts, ["json"])
  end

  if Mix.env() == :dev do
    forward("/sent_emails", Bamboo.SentEmailViewerPlug)
  end

  scope "/", WsdjsWeb do
    pipe_through([:browser, :browser_auth])

    resources("/songs", SongController, only: [:index, :create, :new, :delete, :update]) do
      resources("/videos", SongVideosController, only: [:index, :new, :create, :delete])
      get "/edit", SongActionsController, :edit
    end

    resources("/suggestions", SuggestionController, only: [:create, :new])
    resources("/song_opinions", SongOpinionController, only: [:delete])

    resources "/tops", TopController, only: [:index, :create, :new, :update, :delete] do
      resources("/votes", VoteController, only: [:create])
    end

    get("/tops/:id/stats", TopController, :stat, as: :top_stat)

    resources("/ranks", RankController, only: [:update, :delete])
    resources("/sessions", SessionController, only: [:delete])
    resources("/events", EventController)

    resources "/users", UserController, only: [:index, :edit, :update] do
      resources("/playlists", PlaylistController, only: [:new, :create, :index])
    end

    resources("/user-params", UserParamsController, only: [:show])

    resources("/playlists", PlaylistController, only: [:show, :edit, :delete, :update]) do
      resources("/songs", PlaylistSongsController, only: [:create, :delete, :update])
      resources("/search", PlaylistSearchAddController, only: [:index])
    end
  end

  scope "/", WsdjsWeb do
    # Use the default browser stack
    pipe_through(:browser)

    get("/", HomeController, :index)
    get("/radio", RadioController, :show)
    resources("/users", UserController, only: [:show])
    resources("/home", HomeController, only: [:index])
    resources("/tops", TopController, only: [:show])
    resources("/sessions", SessionController, only: [:new, :create])
    resources("/registrations", RegistrationController, only: [:new, :create])
    get("/signin/:token", SessionController, :show, as: :signin)

    resources("/songs", SongController, only: [:show]) do
      resources("/opinions", OpinionController, only: [:index])
    end

    resources("/api/v1/now_playing", NowPlayingController, only: [:index])
    resources("/api/now_playing", NowPlayingController, only: [:index])
  end

  scope "/", as: :api, alias: :WsdjsApi do
    pipe_through([:api])

    scope "/" do
      get("/.well-known/:page", StaticController, :show)
    end
  end
end

apps/wsdjs_web/lib/wsdjs_web/controllers/user_params_controller.ex
defmodule WsdjsWeb.UserParamsController do
  @moduledoc false
  use WsdjsWeb, :controller

  alias Wsdjs.Accounts

  action_fallback(WsdjsWeb.FallbackController)

  def action(conn, _) do
    args = [conn, conn.params, conn.assigns.current_user]
    apply(__MODULE__, action_name(conn), args)
  end

  @spec show(Plug.Conn.t(), map(), Wsdjs.Accounts.User.t()) ::
          {:error, :unauthorized} | Plug.Conn.t()
  def show(conn, %{"id" => user_id}, current_user) do
    user = Accounts.get_user!(user_id)

    with :ok <- Accounts.Users.can?(current_user, :edit_user, user) do
      changeset = Accounts.change_user(user)

      conn
      |> render(
        "show.html",
        user: user,
        changeset: changeset
      )
    end
  end
end

apps/wsdjs_web/lib/wsdjs_web/views/user_params_view.ex
defmodule WsdjsWeb.UserParamsView do
  use WsdjsWeb, :view
end

apps/wsdjs_web/lib/wsdjs_web/templates/user_params/show.html.eex
<nav class="secondary-nav py-4">
  <ol class="container">
    <li class="inline-block">
      <%= link "bio", to: Routes.user_path(@conn, :show, @user) %>
    </li>
    <li class="inline-block">
      <%= link "playlists", to: Routes.user_playlist_path(@conn, :index, @user) %>
    </li>
    <li class="current inline-block">
      <%= link "params", to: Routes.user_params_path(@conn, :show, @user) %>
    </li>
  </ol>
</nav>

<section class="container pt-4">
  <%= render WsdjsWeb.UserView, "_sidebar.html", conn: @conn, current_user: @current_user, user: @user %>

  <div>
    <%= form_for @changeset, Routes.user_path(@conn, :update, @user), fn f -> %>

      <table class="table">
      <tr>
        <td><strong>Email contact visible</strong><p class="text-grey-darkest">Your user page contains a button to send you an email. Your email is public.</p></td>
        <td>
          <div class="ckbx-style-11 ">
            <%= inputs_for f, :parameter, fn fp -> %>
              <%= checkbox fp, :email_contact %>
              <%= label fp, :email_contact do %><% end %>
            <% end %>
          </div>
        </td>
      </tr>
      <%= if Wsdjs.Accounts.Users.can?(@user, :new_song_notification) == :ok do %>
      <tr>
        <td><strong>New song notification</strong><p class="text-grey-darkest">Receive an email everyday if new songs have been suggeted.</p></td>
        <td>
          <div class="ckbx-style-11 ">
            <%= inputs_for f, :parameter, fn fp -> %>
              <%= checkbox fp, :new_song_notification %>
              <%= label fp, :new_song_notification do %><% end %>
            <% end %>
          </div>
        </td>
      </tr>
      </tbody>
      <% end %>
  
      <%= if @current_user.admin do %>
      <tbody>
      <tr>
      <td colspan="2"><span class="h3">Admin fields</tr></td>
      </tr>
      <tr>
        <td><strong>Profil admin</strong><p class="text-grey-darkest">Master of universe ?</p></td>
        <td>
          <div class="ckbx-style-11 danger">
            <%= checkbox f, :admin %>
            <%= label f,:admin do %><% end %>
          </div>
        </td>
      </tr>
      <tr>
        <td><strong>Verified profil</strong><p class="text-grey-darkest">The user identity has been verified, try to avoid user usurpation</p></td>
        <td>
          <div class=" ckbx-style-11 ">
            <%= checkbox f, :verified_profil %>
            <%= label f,:verified_profil do %><% end %>
          </div>
        </td>
      </tr>
      <tr>
        <td><strong>Profil DJ VIP</strong><p class="text-grey-darkest">Can suggest song, vote for official WSDJs TOP10, access all song suggested and TOP, create personal TOP5</p></td>
        <td>
          <div class=" ckbx-style-11 ">
            <%= checkbox f, :profil_djvip %>
            <%= label f,:profil_djvip do %><% end %>
          </div>
        </td>
      </tr>
      <tr>
        <td><strong>Profil DJ</strong><p class="text-grey-darkest">Can create a personnal TOP5.</p></td>
        <td>
          <div class=" ckbx-style-11 ">
            <%= checkbox f, :profil_dj %>
            <%= label f,:profil_dj do %><% end %>
          </div>
        </td>
      </tr>
      <tr>
        <td><strong>Deactivate user</strong><p class="text-grey-darkest">Desactivate a user, he can't login or receive notifications.</p></td>
        <td>
          <div class=" ckbx-style-11 danger">
            <%= checkbox f, :deactivated %>
            <%= label f,:deactivated do %><% end %>
          </div>
        </td>
      </tr>
      <tr>
        <td><strong>Activate piwik</strong><p class="text-grey-darkest">The user is monitored by piwik.</p></td>
        <td>
          <div class=" ckbx-style-11 ">
            <%= inputs_for f, :parameter, fn fp -> %>
              <%= checkbox fp, :piwik %>
              <%= label fp, :piwik do %><% end %>
            <% end %>
          </div>
        </td>
      </tr> 
      <tr>
        <td><strong>Activate video</strong><p class="text-grey-darkest">The user can add video to a song.</p></td>
        <td>
          <div class=" ckbx-style-11 ">
            <%= inputs_for f, :parameter, fn fp -> %>
              <%= checkbox fp, :video %>
              <%= label fp, :video do %><% end %>
            <% end %>
          </div>
        </td>
      </tr> 
      <tr>
        <td><strong>Radioking umatch</strong><p class="text-grey-darkest">Send an email when a song streamed by radioking does not match with WSDJs database.</p></td>
        <td>
          <div class=" ckbx-style-11 ">
            <%= inputs_for f, :parameter, fn fp -> %>
              <%= checkbox fp, :radioking_unmatch %>
              <%= label fp, :radioking_unmatch do %><% end %>
            <% end %>
          </div>
        </td>
      </tr>
    <% end %>
    </table>
  <%= submit "Update", class: "btn btn-primary" %>

<% end %>
  </div>

  <%= link "log out", to: Routes.session_path(@conn, :delete, @current_user), method: :delete, data: [pjax: "false"], class: "btn btn-link text-danger mt-6" %>

</section>