apps/wsdjs_web/lib/wsdjs_web/router.ex
defmodule WsdjsWeb.Router do
  use WsdjsWeb, :router

  pipeline :browser do
    plug(:accepts, ["html", "text"])
    plug(:fetch_session)
    plug(:fetch_flash)
    plug(:protect_from_forgery)
    plug(:put_secure_browser_headers)
    plug(WsdjsWeb.VerifySession)
    plug(WsdjsWeb.IsAjax)
  end

  pipeline :browser_auth do
    plug(WsdjsWeb.EnsureAuthenticated)
  end

  pipeline :api do
    plug(:accepts, ["json"])
  end

  if Mix.env() == :dev do
    forward("/sent_emails", Bamboo.SentEmailViewerPlug)
  end

  scope "/", WsdjsWeb do
    pipe_through([:browser, :browser_auth])

    resources("/songs", SongController, only: [:index, :create, :new, :delete, :update]) do
      resources("/videos", SongVideosController, only: [:index, :new, :create, :delete])
      get "/edit", SongActionsController, :edit
    end

    resources("/suggestions", SuggestionController, only: [:create, :new])
    resources("/song_opinions", SongOpinionController, only: [:delete])

    resources "/tops", TopController, only: [:index, :create, :new, :update, :delete] do
      resources("/votes", VoteController, only: [:create])
    end

    get("/tops/:id/stats", TopController, :stat, as: :top_stat)

    resources("/ranks", RankController, only: [:update, :delete])
    resources("/sessions", SessionController, only: [:delete])
    resources("/events", EventController)

    resources "/users", UserController, only: [:index, :edit, :update] do
      resources("/playlists", PlaylistController, only: [:new, :create, :index])
    end

    resources("/user-params", UserParamsController, only: [:show])

    resources("/playlists", PlaylistController, only: [:show, :edit, :delete, :update]) do
      resources("/songs", PlaylistSongsController, only: [:create, :delete, :update])
      resources("/search", PlaylistSearchAddController, only: [:index])
    end
  end

  scope "/", WsdjsWeb do
    # Use the default browser stack
    pipe_through(:browser)

    get("/", HomeController, :index)
    get("/radio", RadioController, :show)
    resources("/users", UserController, only: [:show])
    resources("/home", HomeController, only: [:index])
    resources("/tops", TopController, only: [:show])
    resources("/sessions", SessionController, only: [:new, :create])
    resources("/registrations", RegistrationController, only: [:new, :create])
    get("/signin/:token", SessionController, :show, as: :signin)

    resources("/songs", SongController, only: [:show]) do
      resources("/opinions", OpinionController, only: [:index])
    end

    resources("/api/v1/now_playing", NowPlayingController, only: [:index])
    resources("/api/now_playing", NowPlayingController, only: [:index])
  end

  scope "/", as: :api, alias: :WsdjsApi do
    pipe_through([:api])

    scope "/" do
      get("/.well-known/:page", StaticController, :show)
    end
  end
end

apps/wsdjs_web/lib/wsdjs_web/views/layout_view.ex
defmodule WsdjsWeb.LayoutView do
  use WsdjsWeb, :view

  @doc """
  Generates name for the JavaScript view we want to use
  in this combination of view/template.
  """
  def js_view_name(conn, view_template) do
    [view_name(conn), template_name(view_template)]
    |> Enum.reverse()
    |> List.insert_at(0, "view")
    |> Enum.map(&String.capitalize/1)
    |> Enum.reverse()
    |> Enum.join("")
  end

  def active_class(conn, val) do
    if Enum.member?(val, view_name(conn)) do
      "active"
    else
      ""
    end
  end

  # Takes the resource name of the view module and removes the
  # the ending *_view* string.
  defp view_name(conn) do
    conn
    |> view_module
    |> Phoenix.Naming.resource_name()
    |> String.replace("_view", "")
  end

  # Removes the extion from the template and reutrns
  # just the name.
  defp template_name(template) when is_binary(template) do
    template
    |> String.split(".")
    |> Enum.at(0)
  end

  def current_user_id(nil), do: nil
  def current_user_id(%Wsdjs.Accounts.User{} = user), do: user.id

  @suffix "World Swing DJs"

  def main_title(conn) do
    controller = view_name(conn)
    action = action_name(conn)

    get(controller, action)
  end

  def page_title(conn) do
    conn |> main_title() |> put_suffix()
  end

  defp put_suffix(nil), do: @suffix
  defp put_suffix(title), do: title <> " - " <> @suffix

  defp get("home", :index), do: "Home"
  defp get("song", :index), do: "List songs"
  defp get("song", :show), do: "Song"
  defp get("user", :index), do: "List users"
  defp get("user", :show), do: "User"
  defp get("user", :edit), do: "Edit user"
  defp get("top", :index), do: "List tops"

  defp get(_, _), do: nil
end

apps/wsdjs_web/lib/wsdjs_web/templates/layout/_mobile_nav.html.eex
<nav class="mobile-nav z-50">
  <ul class="list-reset">
    <li>
      <%= link to: Routes.top_path(@conn, :index), class: "mobile-nav_menu" do %>
      <svg style="width:24px;height:24px" viewBox="0 0 24 24">
        <path fill="#455A64" d="M20.2,2H19.5H18C17.1,2 16,3 16,4H8C8,3 6.9,2 6,2H4.5H3.8H2V11C2,12 3,13 4,13H6.2C6.6,15 7.9,16.7 11,17V19.1C8.8,19.3 8,20.4 8,21.7V22H16V21.7C16,20.4 15.2,19.3 13,19.1V17C16.1,16.7 17.4,15 17.8,13H20C21,13 22,12 22,11V2H20.2M4,11V4H6V6V11C5.1,11 4.3,11 4,11M20,11C19.7,11 18.9,11 18,11V6V4H20V11Z" />
      </svg>
      <% end %>
    </li>
    <li>
      <%= link to: Routes.song_path(@conn, :index), class: "mobile-nav_menu" do %>
      <svg style="width:24px;height:24px" viewBox="0 0 24 24">
        <path fill="#455A64" d="M4,6H2V20A2,2 0 0,0 4,22H18V20H4M18,7H15V12.5A2.5,2.5 0 0,1 12.5,15A2.5,2.5 0 0,1 10,12.5A2.5,2.5 0 0,1 12.5,10C13.07,10 13.58,10.19 14,10.5V5H18M20,2H8A2,2 0 0,0 6,4V16A2,2 0 0,0 8,18H20A2,2 0 0,0 22,16V4A2,2 0 0,0 20,2Z" />
      </svg>
      <% end %>
    </li>
    <li>
      <%= link to: Routes.radio_path(@conn, :show), class: "mobile-nav_menu" do %>
      
        <svg style="width:24px;height:24px" viewBox="0 0 24 24" class="icon-radio">
          <path fill="#455A64" d="M20,6A2,2 0 0,1 22,8V20A2,2 0 0,1 20,22H4A2,2 0 0,1 2,20V8C2,7.15 2.53,6.42 3.28,6.13L15.71,1L16.47,2.83L8.83,6H20M20,8H4V12H16V10H18V12H20V8M7,14A3,3 0 0,0 4,17A3,3 0 0,0 7,20A3,3 0 0,0 10,17A3,3 0 0,0 7,14Z" />
        </svg>

        <div class="sound-bars">
          <div class="sound-bar"></div>
          <div class="sound-bar"></div>
          <div class="sound-bar"></div>
        </div>

      <% end %>
    </li>
    <%= if Wsdjs.Accounts.Users.can?(@conn.assigns.current_user, :index) == :ok do %>
    <li>
      <%= link to: Routes.user_path(@conn, :index), class: "mobile-nav_menu" do %>
      <svg style="width:24px;height:24px" viewBox="0 0 24 24">
        <path fill="#455A64" d="M16,13C15.71,13 15.38,13 15.03,13.05C16.19,13.89 17,15 17,16.5V19H23V16.5C23,14.17 18.33,13 16,13M8,13C5.67,13 1,14.17 1,16.5V19H15V16.5C15,14.17 10.33,13 8,13M8,11A3,3 0 0,0 11,8A3,3 0 0,0 8,5A3,3 0 0,0 5,8A3,3 0 0,0 8,11M16,11A3,3 0 0,0 19,8A3,3 0 0,0 16,5A3,3 0 0,0 13,8A3,3 0 0,0 16,11Z" />
      </svg>
      <% end %>
    </li>
    <% end %>
    <%= if Wsdjs.Happenings.can?(@conn.assigns.current_user, :index) == :ok do %>
    <li>
      <%= link  to: Routes.event_path(@conn, :index), class: "mobile-nav_menu" do %>
      <svg style="width:24px;height:24px" viewBox="0 0 24 24">
        <path fill="#455A64" d="M19,19H5V8H19M16,1V3H8V1H6V3H5C3.89,3 3,3.89 3,5V19A2,2 0 0,0 5,21H19A2,2 0 0,0 21,19V5C21,3.89 20.1,3 19,3H18V1M17,12H12V17H17V12Z" />
      </svg>
      <% end %>
    </li>
    <% end %>
  </ul>
</nav>

apps/wsdjs_web/lib/wsdjs_web/templates/layout/_piwik.html.eex
<script type="text/javascript">
  var _paq = _paq || [];

  _paq.push(['setCustomUrl', document.location]);
  _paq.push(['setDocumentTitle', document.title]);
  <%= if not is_nil(@current_user) do %>_paq.push(['setUserId', '<%= @current_user.email %>']);<% end %>

  _paq.push(['trackPageView']);
  _paq.push(['enableLinkTracking']);
  (function() {
    var u="https://piwik.radiowcs.com/";
    _paq.push(['setTrackerUrl', u+'piwik.php']);
    _paq.push(['setSiteId', '1']);
    var d=document, g=d.createElement('script'), s=d.getElementsByTagName('script')[0];
    g.type='text/javascript'; g.async=true; g.defer=true; g.src=u+'piwik.js'; s.parentNode.insertBefore(g,s);
  })();
</script>

apps/wsdjs_web/lib/wsdjs_web/templates/layout/_video_player.html.eex
<aside id="player__youtube__container" class="player__youtube__container">
  <button class="player__youtube_close btn btn-reverse">close</button>
  <div id="player__youtube" class="player__youtube"></div>
</aside>

apps/wsdjs_web/lib/wsdjs_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no, user-scalable = no">
    <meta http-equiv="Accept-CH" content="DPR, Viewport-Width, Width">
    <meta name="cloudinary_cloud_name" content="don2kwaju">
    <meta name="description" content="World Swing DeeJays. The best West Coast Swing music from all around the world !">

    <!-- Control the behavior of search engine crawling and indexing -->
    <meta name="robots" content="index,follow"><!-- All Search Engines -->
    <meta name="googlebot" content="index,follow"><!-- Google Specific -->
    <!-- Tells Google not to show the sitelinks search box -->
    <meta name="google" content="nositelinkssearchbox">
    <!-- Tells Google not to provide a translation for this page -->
    <meta name="google" content="notranslate">

    <title><%= page_title(@conn) %></title>
    
    <meta name="apple-mobile-web-app-title" content="WorldSwingDJs">

    <link rel="icon" type="image/png" sizes="16x16" href="https://res.cloudinary.com/don2kwaju/image/upload/c_scale,w_16/fl_immutable_cache/v1503520190/wsdjs/worldswingdjs_single_flat.png">
    <link rel="icon" type="image/png" sizes="32x32" href="https://res.cloudinary.com/don2kwaju/image/upload/c_scale,w_32/fl_immutable_cache/v1503520190/wsdjs/worldswingdjs_single_flat.png">
    <link rel="icon" type="image/png" sizes="96x96" href="https://res.cloudinary.com/don2kwaju/image/upload/c_scale,w_96/fl_immutable_cache/v1503520190/wsdjs/worldswingdjs_single_flat.png">

    <link rel="apple-touch-icon" href="https://res.cloudinary.com/don2kwaju/image/upload/b_rgb:ffffff,c_fit,w_80/v1503520190/wsdjs/worldswingdjs_single_flat.png">
    <link rel="apple-touch-icon" sizes="152x152" href="https://res.cloudinary.com/don2kwaju/image/upload/b_rgb:ffffff,c_fit,w_152/v1503520190/wsdjs/worldswingdjs_single_flat.png">
    <link rel="apple-touch-icon" sizes="180x180" href="https://res.cloudinary.com/don2kwaju/image/upload/b_rgb:ffffff,c_fit,w_180/v1503520190/wsdjs/worldswingdjs_single_flat.png">
    <link rel="apple-touch-icon" sizes="167x167" href="https://res.cloudinary.com/don2kwaju/image/upload/b_rgb:ffffff,c_fit,w_167/v1503520190/wsdjs/worldswingdjs_single_flat.png">

    <meta name="apple-mobile-web-app-capable" content="yes" />
    <link href="https://res.cloudinary.com/don2kwaju/image/upload/b_rgb:1f2532,c_scale,h_2732,w_2048/v1538673297/wsdjs/wsdjs.png" sizes="2048x2732" rel="apple-touch-startup-image" />
    <link href="https://res.cloudinary.com/don2kwaju/image/upload/b_rgb:1f2532,c_scale,h_2224,w_1668/v1538673297/wsdjs/wsdjs.png" sizes="1668x2224" rel="apple-touch-startup-image" />
    <link href="https://res.cloudinary.com/don2kwaju/image/upload/b_rgb:1f2532,c_scale,h_2048,w_1536/v1538673297/wsdjs/wsdjs.png" sizes="1536x2048" rel="apple-touch-startup-image" />
    <link href="https://res.cloudinary.com/don2kwaju/image/upload/b_rgb:1f2532,c_scale,h_2436,w_1125/v1538673297/wsdjs/wsdjs.png" sizes="1125x2436" rel="apple-touch-startup-image" />
    <link href="https://res.cloudinary.com/don2kwaju/image/upload/b_rgb:1f2532,c_scale,h_2208,w_1242/v1538673297/wsdjs/wsdjs.png" sizes="1242x2208" rel="apple-touch-startup-image" />
    <link href="https://res.cloudinary.com/don2kwaju/image/upload/b_rgb:1f2532,c_scale,h_1334,w_750/v1538673297/wsdjs/wsdjs.png" sizes="750x1334" rel="apple-touch-startup-image" />
    <link href="https://res.cloudinary.com/don2kwaju/image/upload/b_rgb:1f2532,c_scale,h_1136,w_640/v1538673297/wsdjs/wsdjs.png" sizes="640x1136" rel="apple-touch-startup-image" />

    <link rel="manifest" href="<%= Routes.static_path(@conn, "/manifest.webmanifest") %>">

    <link defer rel="stylesheet" type="text/css" href="<%= Routes.static_path(@conn, "/css/app.css") %>">
    <script defer src="https://cdn.polyfill.io/v2/polyfill.js?features=IntersectionObserver,fetch,Promise,IntersectionObserverEntry&flags=gated"></script>

    <script defer src="<%= Routes.static_path(@conn, "/js/app.js") %>"></script>
    <script defer src="https://widget.cloudinary.com/global/all.js" type="text/javascript"></script>
    <%= if user = @conn.assigns[:current_user] do %>
    <script>window.userToken = "<%= Phoenix.Token.sign(@conn, "user", user.id) %>"</script>
    <%= tag :meta, name: "channel_token", content: Phoenix.Token.sign(@conn, "user", user.id) %>
    <% end %>
    <script>window.baseApiUrl = "<%= ApiRoutes.base_path() %>"</script>
    <%= render_existing(@view_module, "_meta." <> @view_template, assigns) %>
  </head>

  <body class="font-sans">
    <nav class="glnav md:px-8">
      <div class="container flex flex-wrap items-end">
        <div class="md:hidden logo-small">
          <svg class="logo " fill="#D3D8E0" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 200 200">
            <g>
              <path d="M52.4,165.2c0.5-19.4,1.1-38.6,1.7-58c0.6,0,1.4,0,2.1,0c5.5-0.1,11-0.2,16.5-0.3c1.3,0,2.5,0.1,3.8,0.3c5.5,0.7,8.9,4.2,11.1,9c2.1,4.7,2.9,9.7,3.1,14.8c0.3,7.3-0.4,14.4-2.9,21.3c-0.4,1.3-1,2.5-1.7,3.7c-3,5.8-7.8,9.1-14.5,9.2c-3,0-6.1,0-9.1,0C59.1,165.2,55.7,165.2,52.4,165.2z M63.9,152.4c0.7,0.1,1.3,0.1,1.8,0.2c6.4,0.5,9.9-1.8,11.8-7.9c1.3-4.1,1.6-8.4,1.4-12.6c-0.1-2.7-0.6-5.4-1.8-8c-0.8-1.9-2.1-3.4-4.2-4.1c-2.6-0.8-5.3-0.5-8-0.2C64.6,130.7,64.2,141.4,63.9,152.4z"></path>
              <path d="M91.3,149.8c1,0.5,2,1.1,2.9,1.6c1.1,0.5,2.3,0.9,3.5,1.3c3.7,0.8,6.3-0.6,7.2-4.3c0.6-2.2,0.9-4.6,1-6.9c0.3-6.6,0.4-13.3,0.6-19.8c0.1-4.4,0.1-8.9,0.1-13.3c0-0.3,0-0.6,0.1-1c4,0,7.8,0,11.8,0c0,0.9,0,1.9,0,2.8c-0.4,12.9-0.8,25.9-1.4,38.7c-0.1,2.9-0.4,6.1-1.3,8.9c-1.7,5.4-7.3,8.9-13.3,8.7c-3.4-0.2-6.8-0.8-10-2.1c-0.4-0.1-0.9-0.6-0.9-1c-0.2-4.3-0.4-8.7-0.6-12.9C91.1,150.2,91.2,150,91.3,149.8z"></path>
              <path d="M145.4,134c-2-1-4-2-6.4-1.9c-1.4,0-2.9,0.1-3.5,1.6c-0.7,1.6,0,2.9,1,4.1c1.7,1.9,3.3,3.8,4.9,5.6c3.5,4.5,4.4,9.6,2.8,15.1c-1.6,5.4-6.7,8.6-12.8,7.8c-2.5-0.3-5-1-7.4-1.7c-0.3-0.1-0.8-0.5-0.8-0.8c-0.3-4-0.5-7.9-0.7-12.1c0.8,0.4,1.5,0.8,2.2,1.3c2,1,4,2.1,6.4,1.9c1.1-0.1,2.2-0.4,2.8-1.6c0.6-1.3,0.4-2.4-0.4-3.4c-1.5-1.9-3-3.8-4.6-5.5c-4-4.6-5.3-9.7-3.9-15.6c1.4-5.4,4.7-8.2,10.3-8c3.3,0.1,6.6,0.7,10.2,1.1c0,2.3,0,4.3,0,6.3C145.4,130,145.4,132,145.4,134z"></path>
            </g>
            <path fill="#FFC107" d="M92.7,12.1c19.7-1,36.9,2.6,54.2,13.2c18.6,11.3,28.5,25,33.5,42.7c1.3,4.7,3.1,9.5,3.9,14.4c0.5,3.1,2.8,18.8,2.9,21.9c4.3,8.1,6.4,10.4,7.3,22.1c0.4,5.7,0.5,11.4-1.4,17c-4.6,13.3-8.3,21.9-22.6,26.4c-1.1,0.3-2,1.2-3,1.8c-0.9,0.5-1.6,1.2-2.6,1.5c-3.6,1.3-7.4,1.5-11.2,0.4c-1.7-0.5-2.7-1.5-2.8-3.3c-1.3-24.7-2.5-49.3-3.9-74.1c-0.1-1.5,0.7-2.5,1.9-3c4.5-2.1,9.1-2.4,13.7-0.4c0.8,0.3,1.6,0.7,2.4,0.8c6.8,1,7.2,1.8,11.3,4.5c0.1-5.1-2.6-10.5-2.7-13.6c-1.1,0-2.1-0.1-3.1-0.1c-0.9-4.4-2.5-8.8-3.8-13c-5.4-16.9-10.2-25.3-29.6-35.7s-35.4-10.6-43.7-10c-8.3,0.2-24.2,2.1-42.4,14.5S28.8,61,25.2,78.4c-0.9,4.3-1.9,8.8-2.4,13.3c-1,0.1-2,0.3-3.1,0.5c0.2,3.1-1.9,8.8-1.3,13.8c3.8-3.1,4.2-3.9,10.8-5.6c0.8-0.2,1.6-0.7,2.3-1.1c4.4-2.5,9-2.6,13.7-1c1.3,0.4,2.2,1.2,2.2,2.8c1.2,24.8,2.6,49.4,3.9,74.1c0.1,1.8-0.7,2.9-2.4,3.6c-3.6,1.5-7.4,1.7-11.2,0.8c-1-0.2-1.8-0.8-2.8-1.2c-1-0.5-2.1-1.2-3.2-1.5c-14.8-3-19.3-11.1-25.3-23.9c-2.5-5.3-3-11-3.2-16.7c-0.3-11.7,1.5-14.2,4.9-22.8C8.2,110.4,8.8,94.6,9,91.5c0.2-4.9,1.5-9.9,2.3-14.7c3.1-18.1,11.5-32.7,28.8-45.9C56.2,18.6,73,13.1,92.7,12.1z"></path>
          </svg>
        </div>

        <%= link "Discover", to: Routes.home_path(@conn, :index), class: "h1 glnav__menu hidden md:inline #{active_class(@conn, ["home"])}" %>

        <%= if not is_nil(@conn.assigns.current_user) do %>
          <%= link "Charts", to: Routes.top_path(@conn, :index), class: "glnav__menu hidden md:inline #{active_class(@conn, ["top"])}" %>
          <%= link "Library", to: Routes.song_path(@conn, :index), class: "glnav__menu hidden md:inline  #{active_class(@conn, ["song", "song_videos", "song_actions"])}" %>
        <% end %>
        <%= if Wsdjs.Accounts.Users.can?(@conn.assigns.current_user, :index) == :ok do %>
        <%= link "Members", to: Routes.user_path(@conn, :index), class: "glnav__menu hidden md:inline #{active_class(@conn, ["user", "playlist", "user_params"])}" %>
        <% end %>
        <%= if Wsdjs.Happenings.can?(@conn.assigns.current_user, :index) == :ok do %>
        <%= link "Events", to: Routes.event_path(@conn, :index), class: "glnav__menu hidden md:inline #{active_class(@conn, ["event"])}" %>
        <% end %>

        <%= if @current_user do %>
          <%= link to: Routes.user_path(@conn, :show, @current_user.id), class: "glnav__user" do %>
            <img class="glnav__user__avatar" src="<%= Attachments.avatar_url(@current_user.avatar, 40) %>" srcset="<%= Attachments.avatar_srcset(@current_user.avatar, 50) %>" sizes="50px">
          <% end %>
        <% end %>
      </div>
    </nav>

    <main class="<%= js_view_name(@conn, @view_template) %> flex flex-col justify-between pb-32"
          data-js-view-name="<%= js_view_name(@conn, @view_template) %>"
          data-user-id="<%= current_user_id(@current_user) %>">
      <%= render @view_module, @view_template, assigns %>
    </main>
    
    <%= render "_radio_player.html", conn: @conn %>
    <%= render "_video_player.html", conn: @conn %>
    <%= render "_mobile_nav.html", conn: @conn %>

    <%= render "_desktop-outside.html", conn: @conn, current_user: @current_user %>
  </body>
</html>