apps/wsdjs_web/lib/wsdjs_web/router.ex
defmodule WsdjsWeb.Router do
  use WsdjsWeb, :router

  pipeline :browser do
    plug(:accepts, ["html", "text"])
    plug(:fetch_session)
    plug(:fetch_flash)
    plug(:protect_from_forgery)
    plug(:put_secure_browser_headers)
    plug(WsdjsWeb.VerifySession)
    plug(WsdjsWeb.IsAjax)
  end

  pipeline :browser_auth do
    plug(WsdjsWeb.EnsureAuthenticated)
  end

  pipeline :api do
    plug(:accepts, ["json"])
  end

  if Mix.env() == :dev do
    forward("/sent_emails", Bamboo.SentEmailViewerPlug)
  end

  scope "/", WsdjsWeb do
    pipe_through([:browser, :browser_auth])

    resources("/songs", SongController, only: [:index, :create, :new, :delete, :update]) do
      resources("/videos", SongVideosController, only: [:index, :new, :create, :delete])
      get "/edit", SongActionsController, :edit
    end

    resources("/suggestions", SuggestionController, only: [:create, :new])
    resources("/song_opinions", SongOpinionController, only: [:delete])

    resources "/tops", TopController, only: [:index, :create, :new, :update, :delete] do
      resources("/votes", VoteController, only: [:create])
    end

    get("/tops/:id/stats", TopController, :stat, as: :top_stat)

    resources("/ranks", RankController, only: [:update, :delete])
    resources("/sessions", SessionController, only: [:delete])
    resources("/events", EventController)

    resources "/users", UserController, only: [:index, :edit, :update] do
      resources("/playlists", PlaylistController, only: [:new, :create, :index])
    end

    resources("/user-params", UserParamsController, only: [:show])

    resources("/playlists", PlaylistController, only: [:show, :edit, :delete, :update]) do
      resources("/songs", PlaylistSongsController, only: [:create, :delete, :update])
      resources("/search", PlaylistSearchAddController, only: [:index])
    end
  end

  scope "/", WsdjsWeb do
    # Use the default browser stack
    pipe_through(:browser)

    get("/", HomeController, :index)
    get("/radio", RadioController, :show)
    resources("/users", UserController, only: [:show])
    resources("/home", HomeController, only: [:index])
    resources("/tops", TopController, only: [:show])
    resources("/sessions", SessionController, only: [:new, :create])
    resources("/registrations", RegistrationController, only: [:new, :create])
    get("/signin/:token", SessionController, :show, as: :signin)

    resources("/songs", SongController, only: [:show]) do
      resources("/opinions", OpinionController, only: [:index])
    end

    resources("/api/v1/now_playing", NowPlayingController, only: [:index])
    resources("/api/now_playing", NowPlayingController, only: [:index])
  end

  scope "/", as: :api, alias: :WsdjsApi do
    pipe_through([:api])

    scope "/" do
      get("/.well-known/:page", StaticController, :show)
    end
  end
end

apps/wsdjs_web/lib/wsdjs_web/controllers/song_videos_controller.ex
defmodule WsdjsWeb.SongVideosController do
  @moduledoc false

  use WsdjsWeb, :controller

  alias Wsdjs.Attachments
  alias Wsdjs.Attachments.Videos.Video
  alias Wsdjs.Musics.Songs

  action_fallback(WsdjsWeb.FallbackController)

  def action(conn, _) do
    args = [conn, conn.params, conn.assigns.current_user]
    apply(__MODULE__, action_name(conn), args)
  end

  @spec index(Plug.Conn.t(), any(), Wsdjs.Accounts.User.t()) ::
          {:error, :unauthorized} | Plug.Conn.t()
  def index(conn, %{"song_id" => song_id}, current_user) do
    song = Songs.get_song!(song_id)

    with :ok <- Songs.can?(current_user, :show, song) do
      videos = Attachments.list_videos(song)
      video_changeset = Attachments.change_video(%Video{})

      render(
        conn,
        "index.html",
        song: song,
        videos: videos,
        video_changeset: video_changeset
      )
    end
  end

  def new(conn, %{"song_id" => song_id}, current_user) do
    song = Songs.get_song!(song_id)

    with :ok <- Songs.can?(current_user, :create) do
      changeset = Attachments.change_video(%Video{})
      render(conn, "new.html", changeset: changeset, song: song)
    end
  end

  def create(conn, %{"song_id" => song_id, "video" => params}, current_user) do
    song = Songs.get_song!(song_id)

    params =
      params
      |> Map.put("user_id", current_user.id)
      |> Map.put("song_id", song_id)

    with :ok <- Attachments.Policy.can?(current_user, :create_video),
         {:ok, _} <- Attachments.create_video(params) do
      conn
      |> put_flash(:info, "Video created")
      |> redirect(to: Routes.song_song_videos_path(conn, :index, song))
    end
  end

  def delete(conn, %{"id" => id}, current_user) do
    video = Attachments.get_video!(id)
    song = Songs.get_song!(video.song_id)

    with :ok <- Attachments.Policy.can?(current_user, :delete, video),
         {:ok, _} <- Attachments.delete_video(video) do
      conn
      |> put_flash(:info, "Video deleted")
      |> redirect(to: Routes.song_song_videos_path(conn, :index, song))
    end
  end
end

apps/wsdjs_web/lib/wsdjs_web/views/song_videos_view.ex
defmodule WsdjsWeb.SongVideosView do
  use WsdjsWeb, :view

  alias Wsdjs.Happenings

  def list_events do
    events = Happenings.list_events()
    Enum.map(events, &{&1.name, &1.id})
  end
end

apps/wsdjs_web/lib/wsdjs_web/templates/song_videos/_videos.html.eex
<%= for video <- @videos do %>
<article class="song-page__video block">
  <%= link to: video.url, target: "_blank", class: "aspect-ratio-16/9 relative block hover:opacity-50" do %>
    <img src="<%= Attachments.thumbnail_url(video, 320) %>" srcset="<%= Attachments.thumbnail_srcset(video, 320) %>"  class="absolute pin-t w-full h-full shadow">
  <% end %>
  <div class="mt-2 flex">
    <div>
      <span class="text-bold"><%= video.title %></span>
      <br/>
      <span><%= if is_nil(video.event) do video.event_str else video.event.name end %></span>
    </div>
    <%= if Wsdjs.Attachments.Policy.can?(@conn.assigns[:current_user], :delete, video) == :ok do %>
    <div class="ml-auto">
    <%= link to: Routes.song_song_videos_path(@conn, :delete, @song, video), class: "block", method: "delete", data: [pjax: "false", confirm: "Delete video.\n\nAre you sure ?"] do %>
      <svg fill="#455A64" class="svg-icon" height="24" viewBox="0 0 24 24" width="24" xmlns="http://www.w3.org/2000/svg">
        <path d="M6 19c0 1.1.9 2 2 2h8c1.1 0 2-.9 2-2V7H6v12zM19 4h-3.5l-1-1h-5l-1 1H5v2h14V4z"/>
        <path d="M0 0h24v24H0z" fill="none"/>
      </svg>
    <% end %>
    </div>
    <% end %>

  </div>
</article>
<% end %>

apps/wsdjs_web/lib/wsdjs_web/templates/song_videos/index.html.eex
<nav class="secondary-nav mb-4 py-4">
  <ol class="container">
    <li class="inline-block"><%= link "Song", to: Routes.song_path(@conn, :show, @song) %></li>
    <li class="current inline-block"><%= link "Videos", to: Routes.song_song_videos_path(@conn, :index, @song) %></li>
    <%= if Wsdjs.Musics.Songs.can?(@current_user, :edit, @song) == :ok do %>
    <li class="inline-block"><%= link "Edit", to: Routes.song_song_actions_path(@conn, :edit, @song) %></li>
    <% end %>
  </ol>
</nav>


<section class="container">
  <div class="flex p-2 bg-white shadow mb-4">
    <div>
      <div class="relative w-12 h-12 aspect-ratio-square">
        <img src="<%= Attachments.art_url(@song.art, 48) %>" srcset="<%= Attachments.art_srcset(@song.art, 48) %>" sizes="48px" class="responsive absolute pin-t"/>
      </div>
    </div>
    <div class="pl-4">
      <div>
        <span class="primary-text"><%= @song.title %></span>
        <span class="secondary-text pb-2"><span class="text-grey-darkest">by</span> <%= @song.artist %></span>
      </div>
      <div class="text-grey-darkest"> suggested by <%= link user_displayed_name(@song.user), to: Routes.user_path(@conn, :show, @song.user), class: "visible-link action-link text-grey-darkest inline-block" %>,
        <time datetime="<%= utc_to_local(@song.inserted_at) %>" title="<%= Timex.format!(Timex.to_datetime(@song.inserted_at), "%d %b %Y, %k:%M", :strftime) %>">
          <%= Timex.format!(@song.inserted_at, "%b %Y", :strftime) %>
        </time>
      </div>
    </div>
  </div>
</section>


<section id="overview-video" class="overview-video container">
  <%= if Wsdjs.Attachments.Policy.can?(@current_user, :create_video) == :ok do %>
    <%= link to: Routes.song_song_videos_path(@conn, :new, @song) do %>
      <div class="border border-dashed pt-full relative aspect-ratio-16/9">
        <div class="absolute w-full h-full pin-t p-4 text-center flex flex-col items-center justify-around">
        Add a new video
        <svg width="40" height="40" viewBox="0 0 24 24">
          <path d="M19 13h-6v6h-2v-6H5v-2h6V5h2v6h6v2z"/><path d="M0 0h24v24H0z" fill="none"/>
        </svg>
        </div>
      </div>
    <% end %>
  <% end %>

  <%= render @view_module, "_videos.html", conn: @conn, song: @song, videos: Enum.reverse(@videos), changeset: @video_changeset %>
</section>

apps/wsdjs_web/lib/wsdjs_web/templates/song_videos/new.html.eex
<nav class="secondary-nav mb-4 py-4">
  <ol class="container">
    <li class="current inline-block"><%= link "Return to videos list", to: Routes.song_song_videos_path(@conn, :index, @song) %></li>
  </ol>
</nav>

<section class="container">
  <div class="flex p-2 bg-white shadow mb-4">
    <div>
      <img src="<%= Attachments.art_url(@song.art, 48) %>" srcset="<%= Attachments.art_srcset(@song.art, 48) %>" sizes="48px" class="responsive"/>
    </div>
    <div class="pl-4">
      <div>
        <span class="primary-text"><%= @song.title %></span>
        <span class="secondary-text pb-2"><span class="text-grey-darkest">by</span> <%= @song.artist %></span>
      </div>
      <div class="text-grey-darkest"> suggested by <%= link user_displayed_name(@song.user), to: Routes.user_path(@conn, :show, @song.user), class: "visible-link action-link text-grey-darkest inline-block" %>,
        <time datetime="<%= utc_to_local(@song.inserted_at) %>" title="<%= Timex.format!(Timex.to_datetime(@song.inserted_at), "%d %b %Y, %k:%M", :strftime) %>">
          <%= Timex.format!(@song.inserted_at, "%b %Y", :strftime) %>
        </time>
      </div>
    </div>
  </div>
</section>

<%= form_for @changeset, Routes.song_song_videos_path(@conn, :create, @song), [id: "song-video-form", class: "container"], fn f -> %>
  <fieldset class="p-2 border-0 shadow-inner mb-8">
    <legend class="px-2">Add a video</legend>
    <div class="form-group">
      <%= text_input f, :url, type: "url", class: "form-control", placeholder: "Video url", required: true, maxlength: 255 %>
      <%= error_tag f, :url %>
    </div>
    <div class="form-group">
      <%= text_input f, :title, class: "form-control", placeholder: "Pro's names", required: true, maxlength: 255 %>
      <%= error_tag f, :title %>
    </div>
    <div class="form-group">
      <%= select f, :event_id, list_events(), class: "form-control" %>
      <%= error_tag f, :event_id %>
    </div>
  </fieldset>

  <%= submit "Add video", class: "btn btn-primary" %>
<% end %>