apps/wsdjs_web/lib/wsdjs_web/router.ex
defmodule WsdjsWeb.Router do
  use WsdjsWeb, :router

  pipeline :browser do
    plug(:accepts, ["html", "text"])
    plug(:fetch_session)
    plug(:fetch_flash)
    plug(:protect_from_forgery)
    plug(:put_secure_browser_headers)
    plug(WsdjsWeb.VerifySession)
    plug(WsdjsWeb.IsAjax)
  end

  pipeline :browser_auth do
    plug(WsdjsWeb.EnsureAuthenticated)
  end

  pipeline :api do
    plug(:accepts, ["json"])
  end

  if Mix.env() == :dev do
    forward("/sent_emails", Bamboo.SentEmailViewerPlug)
  end

  scope "/", WsdjsWeb do
    pipe_through([:browser, :browser_auth])

    resources("/songs", SongController, only: [:index, :create, :new, :delete, :update]) do
      resources("/videos", SongVideosController, only: [:index, :new, :create, :delete])
      get "/edit", SongActionsController, :edit
    end

    resources("/suggestions", SuggestionController, only: [:create, :new])
    resources("/song_opinions", SongOpinionController, only: [:delete])

    resources "/tops", TopController, only: [:index, :create, :new, :update, :delete] do
      resources("/votes", VoteController, only: [:create])
    end

    get("/tops/:id/stats", TopController, :stat, as: :top_stat)

    resources("/ranks", RankController, only: [:update, :delete])
    resources("/sessions", SessionController, only: [:delete])
    resources("/events", EventController)

    resources "/users", UserController, only: [:index, :edit, :update] do
      resources("/playlists", PlaylistController, only: [:new, :create, :index])
    end

    resources("/user-params", UserParamsController, only: [:show])

    resources("/playlists", PlaylistController, only: [:show, :edit, :delete, :update]) do
      resources("/songs", PlaylistSongsController, only: [:create, :delete, :update])
      resources("/search", PlaylistSearchAddController, only: [:index])
    end
  end

  scope "/", WsdjsWeb do
    # Use the default browser stack
    pipe_through(:browser)

    get("/", HomeController, :index)
    get("/radio", RadioController, :show)
    resources("/users", UserController, only: [:show])
    resources("/home", HomeController, only: [:index])
    resources("/tops", TopController, only: [:show])
    resources("/sessions", SessionController, only: [:new, :create])
    resources("/registrations", RegistrationController, only: [:new, :create])
    get("/signin/:token", SessionController, :show, as: :signin)

    resources("/songs", SongController, only: [:show]) do
      resources("/opinions", OpinionController, only: [:index])
    end

    resources("/api/v1/now_playing", NowPlayingController, only: [:index])
    resources("/api/now_playing", NowPlayingController, only: [:index])
  end

  scope "/", as: :api, alias: :WsdjsApi do
    pipe_through([:api])

    scope "/" do
      get("/.well-known/:page", StaticController, :show)
    end
  end
end

apps/wsdjs_web/lib/wsdjs_web/controllers/home_controller.ex
defmodule WsdjsWeb.HomeController do
  @moduledoc false
  use WsdjsWeb, :controller

  alias Wsdjs.Charts
  alias Wsdjs.Musics

  @spec index(Plug.Conn.t(), any()) :: Plug.Conn.t()
  def index(conn, _params) do
    songs = Musics.Songs.instant_hits()
    top = Charts.last_top(conn.assigns.current_user)
    users = Wsdjs.Accounts.list_djs()

    render(conn, "index.html", songs: songs, top: top, users: users)
  end
end

apps/wsdjs_web/lib/wsdjs_web/views/home_view.ex
defmodule WsdjsWeb.HomeView do
  use WsdjsWeb, :view

  def group_song_by_month(songs) do
    songs
    |> Enum.group_by(fn song -> month_from_date(song.inserted_at) end)
    |> Enum.sort_by(fn {dt, _} -> Date.to_erl(dt) end, &>=/2)
  end

  def month_from_date(date) do
    {:ok, month} = Date.new(date.year, date.month, 1)
    month
  end
end

apps/wsdjs_web/lib/wsdjs_web/templates/home/_not_connected.html.eex
<div class="bg-grey-lightest pt-16 pb-8">
  <div class="container">
    <span class="h1 tracking-wide">World Swing DeeJays</span>
    <span class="h2 block mb-8 font-thin">The best West Coast Swing music from all around the world !</span>

    <%= link to: Routes.session_path(@conn, :new), class: "mr-4" do %>
      <div class="btn btn-primary" title="You can register and sign in with this link">Sign in</div>
    <% end %>
    <span class="mr-4">or</span>
    <%= link "register", to: Routes.registration_path(@conn, :new), class: "inline-block visible-link" %>

    <div class="mt-8">
      <iframe src="https://www.facebook.com/plugins/like.php?href=https%3A%2F%2Fwww.facebook.com%2FWorld-Swing-DJs-1430112430533570%2F&width=85&layout=button_count&action=like&size=small&show_faces=true&share=false&height=21&appId" 
          width="103" height="21" 
          style="border:none;overflow:hidden" 
          scrolling="no" frameborder="0" allowTransparency="true"></iframe>
    </div>

  </div>
</div>

apps/wsdjs_web/lib/wsdjs_web/templates/home/_song.html.eex
<%= if blur_track(@rank.song, @current_user) == true do %>

<li  style="grid-row: 1">
  <a class="carousel-item">
    <div class="relative rounded-lg shadow overflow-hidden">
      <div class="voting-position charted">
        <div class="chart-bg"></div>
        <div class="chart-value"><%= @rank.position %></div>
      </div>
      <img src="<%= Attachments.art_url(nil, 200) %>" class="responsive" />
      <img class="w-8 rounded-full absolute pin-b pin-r border-2 border-white m-1 shadow" src="<%= Attachments.avatar_url(@rank.song.user.avatar, 40) %>" srcset="<%= Attachments.avatar_srcset(@rank.song.user.avatar, 50) %>" sizes="50px">
    </div>


    <div class="song-minicard__body flex pt-2">
      <span class="text-grey-darkest text-ellipsis truncate">hidden track</span>

      <footer>
        <span class="label label-default"><%= @rank.song.genre %></span>
        <%= if @rank.song.bpm > 0 do %>
          <span class="label label-primary"><%= @rank.song.bpm %> bpm</span>
        <% end %>
      </footer>
    </div>
  </a>
</li>

<% else %>

<li style="grid-row: 1">
  <a href="<%= Routes.song_path(@conn, :show, @rank.song.id) %>" class="carousel-item">
    <div class="relative rounded-lg shadow overflow-hidden">
      <div class="voting-position charted">
        <div class="chart-bg"></div>
        <div class="chart-value"><%= @rank.position %></div>
      </div>
      <img src="<%= Attachments.art_url(@rank.song.art, 200) %>" srcset="<%= Attachments.art_srcset(@rank.song.art, 200) %>" class="rounded-lg hover:opacity-50 carousel-item-img" />
  
      <img class="w-8 rounded-full absolute pin-b pin-r border-2 border-white m-1 shadow tippy" data-tippy="<%= user_displayed_name(@rank.song.user) %>" src="<%= Attachments.avatar_url(@rank.song.user.avatar, 40) %>" srcset="<%= Attachments.avatar_srcset(@rank.song.user.avatar, 50) %>" sizes="50px">
    </div>

    <div class="song-minicard__body flex pt-2">
      <span class="primary-text text-ellipsis truncate"><%= @rank.song.title %></span>
      <span class="secondary-text text-ellipsis truncate"><%= @rank.song.artist %></span>
      <span class="text-grey-darkest"><%= user_displayed_name(@rank.song.user) %></span>

      <footer>
        <span class="label label-default"><%= @rank.song.genre %></span>
        <%= if @rank.song.bpm > 0 do %>
          <span class="label label-primary"><%= @rank.song.bpm %> bpm</span>
        <% end %>
      </footer>
    </div>
  </a>
</li>

<% end %>

apps/wsdjs_web/lib/wsdjs_web/templates/home/_song_minicard.html.eex
<%= if blur_track(@song, @current_user) == true do %>

<li class="hover:shadow mr-4 w-48 flex-no-grow flex-no-shrink">
  <a class="carousel-item">
    <div class="relative">
      <img src="<%= Attachments.art_url(nil, 200) %>" class="responsive" />
      <img class="w-8 rounded-full absolute pin-b pin-r border-2 border-white m-1 shadow" src="<%= Attachments.avatar_url(@song.user.avatar, 40) %>" srcset="<%= Attachments.avatar_srcset(@song.user.avatar, 50) %>" sizes="50px">
    </div>
    <div class="song-minicard__body flex pt-2">
      <span class="text-grey-darkest text-ellipsis truncate">hidden track</span>

      <footer>
        <span class="label label-default"><%= @song.genre %></span>
        <%= if @song.bpm > 0 do %>
          <span class="label label-primary"><%= @song.bpm %> bpm</span>
        <% end %>
      </footer>
    </div>
  </a>
</li>

<% else %>

<li class="overflow-hidden" style="grid-row: 1">
  <a href="<%= Routes.song_path(@conn, :show, @song.id) %>" class="carousel-item">
    <div class="relative">
      <img src="<%= Attachments.art_url(@song.art, 200) %>" srcset="<%= Attachments.art_srcset(@song.art, 200) %>" class="rounded-lg shadow hover:opacity-50 carousel-item-img" />
      <img class="w-8 rounded-full absolute pin-b pin-r border-2 border-white m-1 shadow tippy"  data-tippy="<%= user_displayed_name(@song.user) %>"  src="<%= Attachments.avatar_url(@song.user.avatar, 40) %>" srcset="<%= Attachments.avatar_srcset(@song.user.avatar, 50) %>" sizes="50px">
    </div>
    <div class="song-minicard__body flex pt-2">
      <span class="primary-text text-ellipsis truncate"><%= @song.title %></span>
      <span class="secondary-text text-ellipsis truncate"><%= @song.artist %></span>
      <span class="text-grey-darkest text-ellipsis truncate"><%= gettext "by" %> <%= user_displayed_name(@song.user) %></span>

      <footer>
        <span class="label label-default"><%= @song.genre %></span>
        <%= if @song.bpm > 0 do %>
          <span class="label label-primary"><%= @song.bpm %> bpm</span>
        <% end %>
      </footer>
    </div>
  </a>
</li>

<% end %>

apps/wsdjs_web/lib/wsdjs_web/templates/home/_user.html.eex
<li style="grid-row: 1">
  <a href="<%= Routes.user_path(@conn, :show, @user) %>">
    <div class="aspect-ratio-square relative mb-2">
      <img src="<%= Attachments.art_url(@user.avatar, 200) %>" srcset="<%= Attachments.art_srcset(@user.avatar, 200) %>" class="absolute pin-t responsive rounded-lg rounded-full shadow hover:opacity-50 " />
    </div>
    <span class="block text-center"><%= @user.name %></span>
  </a>
</li>

apps/wsdjs_web/lib/wsdjs_web/templates/home/index.html.eex
<%= if is_nil(@current_user) do %>
  <%= render "_not_connected.html", conn: @conn%>
<% end %>

<section class="container">
<%= if Enum.count(@songs) > 0 do %>
  <section class="carousel mt-12">
    <div class="flex items-end justify-between">
      <h2>#trends</h2>
      <div class="carousel-controls whitespace-no-wrap">
        <button class="carousel-control carousel-prev disabled" type="button">
          <svg class="svg-icon" height="16" width="16" viewBox="0 0 12 12" aria-hidden="true"><g><path d="M4.00017708,5.98684317 C3.99681925,5.84078825 4.05038488,5.70791994 4.13783464,5.60205861 L5.73305973,2.95634347 L7.32828482,0.310628317 C7.7589241,-0.403596201 8.83051001,0.242212541 8.39987073,0.956437059 L6.88291326,3.47234368 L5.36595579,5.9882503 L8.40053527,11.0447071 C8.82970125,11.7598174 7.75678626,12.4034167 7.32762028,11.6883064 L4.13704111,6.37191056 C4.04980977,6.26586926 3.99651816,6.13289086 4.00017708,5.98684317 L4.00017708,5.98684317 L4.00017708,5.98684317 Z"></path></g></svg>
          <span class="sr-only">Back</span>
        </button><button class="carousel-control carousel-next" type="button">
          <svg class="svg-icon" height="16" width="16" viewBox="0 0 12 12" aria-hidden="true"><g><path d="M8.49982292,5.98684317 C8.50318075,5.84078825 8.44961512,5.70791994 8.36216536,5.60205861 L6.76694027,2.95634347 L5.17171518,0.310628317 C4.7410759,-0.403596201 3.66948999,0.242212541 4.10012927,0.956437059 L5.61708674,3.47234368 L7.13404421,5.9882503 L4.09946473,11.0447071 C3.67029875,11.7598174 4.74321374,12.4034167 5.17237972,11.6883064 L8.36295889,6.37191056 C8.45019023,6.26586926 8.50348184,6.13289086 8.49982292,5.98684317 L8.49982292,5.98684317 Z"></path></g></svg>
          <span class="sr-only">Next</span>
        </button>
      </div>
    </div>
    <div data-simplebar>
      <ul class="list-reset carousel-items mt-4">
        <%= render_many @songs, WsdjsWeb.HomeView, "_song_minicard.html", conn: @conn, as: :song, current_user: @current_user %>
      </ul>
    </div>
  </section>
<% end %>

<%= if @top && Enum.count(@top.ranks) > 0 do %>
  <section class="carousel mt-12">
    <div class="flex items-end">
      <h2 class="mb-4">
        <time class="date-format" datetime="<%= Date.to_iso8601(@top.due_date) %>">
            <%= Timex.format!(@top.due_date, "%B %Y", :strftime) %>
        </time>, DJs Top
      </h2>
      <%= link "details", to: Routes.top_path(@conn, :show, @top), class: "ml-2 mb-6 @apply border-b-2 border-solid border-yellow-dark" %>
      <div class="carousel-controls mb-4 whitespace-no-wrap ml-auto">
        <button class="carousel-control carousel-prev disabled" type="button">
          <svg class="svg-icon" height="16" width="16" viewBox="0 0 12 12" aria-hidden="true"><g><path d="M4.00017708,5.98684317 C3.99681925,5.84078825 4.05038488,5.70791994 4.13783464,5.60205861 L5.73305973,2.95634347 L7.32828482,0.310628317 C7.7589241,-0.403596201 8.83051001,0.242212541 8.39987073,0.956437059 L6.88291326,3.47234368 L5.36595579,5.9882503 L8.40053527,11.0447071 C8.82970125,11.7598174 7.75678626,12.4034167 7.32762028,11.6883064 L4.13704111,6.37191056 C4.04980977,6.26586926 3.99651816,6.13289086 4.00017708,5.98684317 L4.00017708,5.98684317 L4.00017708,5.98684317 Z"></path></g></svg>
          <span class="sr-only">Back</span>
        </button><button class="carousel-control carousel-next" type="button">
          <svg class="svg-icon" height="16" width="16" viewBox="0 0 12 12" aria-hidden="true"><g><path d="M8.49982292,5.98684317 C8.50318075,5.84078825 8.44961512,5.70791994 8.36216536,5.60205861 L6.76694027,2.95634347 L5.17171518,0.310628317 C4.7410759,-0.403596201 3.66948999,0.242212541 4.10012927,0.956437059 L5.61708674,3.47234368 L7.13404421,5.9882503 L4.09946473,11.0447071 C3.67029875,11.7598174 4.74321374,12.4034167 5.17237972,11.6883064 L8.36295889,6.37191056 C8.45019023,6.26586926 8.50348184,6.13289086 8.49982292,5.98684317 L8.49982292,5.98684317 Z"></path></g></svg>
          <span class="sr-only">Next</span>
        </button>
      </div>
    </div>
    <div data-simplebar>
      <ul class="list-reset carousel-items mt-4">
        <%= for rank <- @top.ranks do %>
          <%= render "_song.html", conn: @conn, rank: rank, current_user: @current_user %>
        <% end %>
      </ul>
    </div>
  </section>
<% end %>

  <section class="carousel mt-12">
    <div class="flex items-end justify-between">
      <h2 class="mb-4">DeeJays</h2>
      <div class="carousel-controls mb-4">
        <button class="carousel-control carousel-prev disabled" type="button">
          <svg class="svg-icon" height="16" width="16" viewBox="0 0 12 12" aria-hidden="true"><g><path d="M4.00017708,5.98684317 C3.99681925,5.84078825 4.05038488,5.70791994 4.13783464,5.60205861 L5.73305973,2.95634347 L7.32828482,0.310628317 C7.7589241,-0.403596201 8.83051001,0.242212541 8.39987073,0.956437059 L6.88291326,3.47234368 L5.36595579,5.9882503 L8.40053527,11.0447071 C8.82970125,11.7598174 7.75678626,12.4034167 7.32762028,11.6883064 L4.13704111,6.37191056 C4.04980977,6.26586926 3.99651816,6.13289086 4.00017708,5.98684317 L4.00017708,5.98684317 L4.00017708,5.98684317 Z"></path></g></svg>
          <span class="sr-only">Back</span>
        </button><button class="carousel-control carousel-next" type="button">
          <svg class="svg-icon" height="16" width="16" viewBox="0 0 12 12" aria-hidden="true"><g><path d="M8.49982292,5.98684317 C8.50318075,5.84078825 8.44961512,5.70791994 8.36216536,5.60205861 L6.76694027,2.95634347 L5.17171518,0.310628317 C4.7410759,-0.403596201 3.66948999,0.242212541 4.10012927,0.956437059 L5.61708674,3.47234368 L7.13404421,5.9882503 L4.09946473,11.0447071 C3.67029875,11.7598174 4.74321374,12.4034167 5.17237972,11.6883064 L8.36295889,6.37191056 C8.45019023,6.26586926 8.50348184,6.13289086 8.49982292,5.98684317 L8.49982292,5.98684317 Z"></path></g></svg>
          <span class="sr-only">Next</span>
        </button>
      </div>
    </div>
    <div data-simplebar id="a">
      <ul class="list-reset carousel-items mt-4">
        <%= for user <- @users do %>
          <%= render "_user.html", conn: @conn, user: user, current_user: @current_user %>
        <% end %>
      </ul>
    </div>
  </section>
</section>